-- LÖSCHE ALTE TABELLEN (erst alle alten Policies/RLS entfernen)
DROP POLICY IF EXISTS "Users read own profile" ON profiles;
DROP POLICY IF EXISTS "Users update own profile" ON profiles;
DROP POLICY IF EXISTS "Insert own profile" ON profiles;
DROP POLICY IF EXISTS "School admins read school profiles" ON profiles;
DROP POLICY IF EXISTS "Admins manage school users" ON profiles;
DROP POLICY IF EXISTS "Anyone can read schools" ON schools;
DROP POLICY IF EXISTS "Admins manage schools" ON schools;
DROP POLICY IF EXISTS "Anyone can insert requests" ON school_requests;
DROP POLICY IF EXISTS "Admins read requests" ON school_requests;
DROP POLICY IF EXISTS "Admins update requests" ON school_requests;
DROP POLICY IF EXISTS "School members read classes" ON classes;
DROP POLICY IF EXISTS "Admins manage classes" ON classes;
DROP POLICY IF EXISTS "School scoped subjects" ON subjects;
DROP POLICY IF EXISTS "School scoped timetable" ON timetable;
DROP POLICY IF EXISTS "School scoped homework" ON homework;
DROP POLICY IF EXISTS "School scoped grades" ON grades;
DROP POLICY IF EXISTS "School scoped exams" ON exams;
DROP POLICY IF EXISTS "School scoped events" ON calendar_events;
DROP POLICY IF EXISTS "School scoped substitutions" ON substitutions;
DROP POLICY IF EXISTS "School scoped messages" ON messages;
DROP POLICY IF EXISTS "School scoped notifications" ON notifications;
DROP POLICY IF EXISTS "School scoped tests" ON tests;
DROP POLICY IF EXISTS "School scoped questions" ON test_questions;
DROP POLICY IF EXISTS "School scoped submissions" ON test_submissions;
DROP POLICY IF EXISTS "School scoped answers" ON test_answers;

DROP TABLE IF EXISTS test_answers CASCADE;
DROP TABLE IF EXISTS test_submissions CASCADE;
DROP TABLE IF EXISTS test_questions CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS substitutions CASCADE;
DROP TABLE IF EXISTS calendar_events CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS homework CASCADE;
DROP TABLE IF EXISTS timetable CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS school_requests CASCADE;
DROP TABLE IF EXISTS schools CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
